// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSF3RLTrTacG9tdnzoa_osgdSr0yRBGMo',
    appId: '1:181724732630:web:103d81689f601c2cd5bd77',
    messagingSenderId: '181724732630',
    projectId: 'cs310-project-cdf40',
    authDomain: 'cs310-project-cdf40.firebaseapp.com',
    storageBucket: 'cs310-project-cdf40.firebasestorage.app',
    measurementId: 'G-HRBPTJQVQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDewGtG9mS6OaGn1Etk2uiS5_t9ll8rx0A',
    appId: '1:181724732630:android:98c1c2b6c2f63250d5bd77',
    messagingSenderId: '181724732630',
    projectId: 'cs310-project-cdf40',
    storageBucket: 'cs310-project-cdf40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8FAuV2OtdD8FYVfHMa1rxNWW64Haom88',
    appId: '1:181724732630:ios:77a811bf1e84a831d5bd77',
    messagingSenderId: '181724732630',
    projectId: 'cs310-project-cdf40',
    storageBucket: 'cs310-project-cdf40.firebasestorage.app',
    iosBundleId: 'com.example.perpetua',
  );
}
